spring.application.name=TaskManajemet


spring.datasource.url=jdbc:postgresql://localhost:5436/taskmanajementdb
spring.datasource.username=yo
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop